---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-https
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usersecrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi