apiVersion: v1
kind: Service
metadata:
  name: eshopwebmvc
spec:
  selector:
    app: eshopwebmvc
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 5106
---
apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi
spec:
  selector:
    app: eshoppublicapi
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 5200
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
