apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopwebmvc
spec:
  template:
    spec:
      containers:
      - name: eshopwebmvc
        image: ${DOCKER_REGISTRY-}eshopwebmvc
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aspnet-https
          mountPath: /root/.aspnet/https
          readOnly: true
        - name: usersecrets
          mountPath: /root/.microsoft/usersecrets
          readOnly: true
        environment:
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker
        - name: ASPNETCORE_URLS
          value: http://+:8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoppublicapi
spec:
  template:
    spec:
      containers:
      - name: eshoppublicapi
        image: ${DOCKER_REGISTRY-}eshoppublicapi
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: aspnet-https
          mountPath: /root/.aspnet/https
          readOnly: true
        - name: usersecrets
          mountPath: /root/.microsoft/usersecrets
          readOnly: true
        environment:
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker
        - name: ASPNETCORE_URLS
          value: http://+:8080

---
apiVersion: v1
kind: Service
metadata:
  name: eshopwebmvc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 5106
  selector:
    app: eshopwebmvc

---
apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 5200
  selector:
    app: eshoppublicapi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-https
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usersecrets
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
